version: "3"

services:
 
  db:
    container_name: "db"
    image: mysql:5.7.31
    restart: always
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_USER= root
      - MYSQL_ROOT_PASSWORD= root
      - MYSQL_DATABASE=employee
      - MYSQL_USER= root
      - MYSQL_PASSWORD= root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    networks:
      - backend
  app:
    build: .
    command: sh -c "/wait && python app/prestart.py && python app/prendas.py"
    ports:
      - "8001:8001"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    #  volumes:
    #    - .:/usr/app
    depends_on:
      - db
    networks:
      - backend
      
networks:
  backend:
    name: backend
    driver: bridge
