version: "3"

services:
 
  recomendador:
    build: .
    command: python main.py
    ports:
      - "8090:8090"
    networks:
      - backend
      
networks:
  backend:
      name: backend
      driver: bridge
